// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

#define PICO_RMII_ETHERNET_SM_RX 1
#define PICO_RMII_ETHERNET_SM_TX 0
#define PICO_RMII_ETHERNET_RX_PIN 12
#define PICO_RMII_ETHERNET_TX_PIN 26
#define PICO_RMII_ETHERNET_RETCLK_PIN 21
#define PICO_RMII_ETHERNET_RST_PIN 20

// ------------------------- //
// rmii_ethernet_phy_rx_data //
// ------------------------- //

#define rmii_ethernet_phy_rx_data_wrap_target 0
#define rmii_ethernet_phy_rx_data_wrap 4
#define rmii_ethernet_phy_rx_data_pio_version 1

static const uint16_t rmii_ethernet_phy_rx_data_program_instructions[] = {
            //     .wrap_target
    0x20a2, //  0: wait   1 pin, 2
    0x22a1, //  1: wait   1 pin, 1               [2]
    0x4002, //  2: in     pins, 2
    0x00c2, //  3: jmp    pin, 2
    0xc000, //  4: irq    nowait 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program rmii_ethernet_phy_rx_data_program = {
    .instructions = rmii_ethernet_phy_rx_data_program_instructions,
    .length = 5,
    .origin = -1,
    .pio_version = rmii_ethernet_phy_rx_data_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config rmii_ethernet_phy_rx_data_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + rmii_ethernet_phy_rx_data_wrap_target, offset + rmii_ethernet_phy_rx_data_wrap);
    return c;
}

static inline void rmii_ethernet_phy_rx_init(PIO pio, uint sm, uint offset, uint pin, float div) {
    // Make RX[1:0], CRS_DV inputs
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 3, false);
    // Make RMII clock an input
    pio_sm_set_consecutive_pindirs(pio, sm, PICO_RMII_ETHERNET_RETCLK_PIN,
    				   1, false);
    pio_sm_config c = rmii_ethernet_phy_rx_data_program_get_default_config(offset);
    sm_config_set_in_pins(&c, pin);
    // Set jump pin to CR_DV
    sm_config_set_jmp_pin(&c, pin+2);
    pio_gpio_init(pio, pin);      // RX0
    pio_gpio_init(pio, pin + 1);  // RX1
    pio_gpio_init(pio, pin + 2);  // CRS (data valid)
    // Disable synchronizers - remove two clock delays...
    //hw_clear_bits(&pio->input_sync_bypass, 0x7u << pin);
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_RX);
    sm_config_set_in_shift(&c, true, true, 8);
    // Run at given RMII clock multiplier
    sm_config_set_clkdiv(&c, div);
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

#endif

