// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------------------- //
// rmii_ethernet_phy_tx_data //
// ------------------------- //

#define rmii_ethernet_phy_tx_data_wrap_target 0
#define rmii_ethernet_phy_tx_data_wrap 11
#define rmii_ethernet_phy_tx_data_pio_version 1

static const uint16_t rmii_ethernet_phy_tx_data_program_instructions[] = {
            //     .wrap_target
    0xe500, //  0: set    pins, 0         side 0 [5]
    0x80a0, //  1: pull   block           side 0
    0x20a0, //  2: wait   1 pin, 0        side 0
    0xff01, //  3: set    pins, 1         side 1 [15]
    0xbf42, //  4: nop                    side 1 [15]
    0xff29, //  5: set    x, 9            side 1 [15]
    0xbd42, //  6: nop                    side 1 [13]
    0xf103, //  7: set    pins, 3         side 1 [1]
    0x7002, //  8: out    pins, 2         side 1
    0x10e8, //  9: jmp    !osre, 8        side 1
    0xe700, // 10: set    pins, 0         side 0 [7]
    0x074b, // 11: jmp    x--, 11         side 0 [7]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program rmii_ethernet_phy_tx_data_program = {
    .instructions = rmii_ethernet_phy_tx_data_program_instructions,
    .length = 12,
    .origin = -1,
    .pio_version = rmii_ethernet_phy_tx_data_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config rmii_ethernet_phy_tx_data_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + rmii_ethernet_phy_tx_data_wrap_target, offset + rmii_ethernet_phy_tx_data_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}

static inline void rmii_ethernet_phy_tx_init(PIO pio, uint sm, uint offset, uint base_pin, uint retclk_pin, float div) {
    // Set the TX_[0,1,EN] in PIO mode
    // Note: do not set RETCLK pin here, it's used as a clock output and only as an input in the PIO program
    pio_gpio_init(pio, base_pin);
    pio_gpio_init(pio, base_pin + 1);
    pio_gpio_init(pio, base_pin + 2);
    // Set RETCLK pin as input
    pio_sm_set_pins_with_mask(pio, sm, 1<<retclk_pin, 0<<retclk_pin);
    // Set TX_[0,1,EN] as output
    pio_sm_set_consecutive_pindirs(pio, sm, base_pin, 3, true);
    pio_sm_config c = rmii_ethernet_phy_tx_data_program_get_default_config(offset);
    sm_config_set_in_pins(&c, retclk_pin);
    sm_config_set_out_pins(&c, base_pin, 2);
    sm_config_set_set_pins(&c, base_pin, 2);
    sm_config_set_sideset_pins(&c, base_pin + 2);
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_TX);
    sm_config_set_out_shift(&c, true, true, 8);
    sm_config_set_in_shift(&c, false, false, 32);
    sm_config_set_clkdiv(&c, div);
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

#endif

